In [406]:
import numpy.matlib
import numpy as np
import math
from typing import Tuple
from collections import namedtuple

Hexahedron = namedtuple('Hexahedron', ['ke_lambda', 'fe_lambda', 'ke_mu', 'fe_mu'])

class Homogenization:
    def __init__(self, 
        cell_len_x: int, 
        cell_len_y: int, 
        cell_len_z: int, 
        lambda_: Tuple[float, float], 
        mu: Tuple[float, float], 
        voxel: np.array
    ):
        self.cell_len_x = cell_len_x
        self.cell_len_y = cell_len_y
        self.cell_len_z = cell_len_z

        self.lambda_ = lambda_
        self.mu = mu
        self.voxel = voxel

        # 6 x 6 Constitutive Tensor
        self.constitutuve_tensor = np.zeros(6)

    def homogenize(self):
        ## Initialize
        # Begin discretization
        n_el_x, n_el_y, n_el_z = self.voxel.shape
        n_el = n_el_x * n_el_y * n_el_z
        dx = self.cell_len_x / n_el_x
        dy = self.cell_len_y / n_el_y
        dz = self.cell_len_z / n_el_z

        # The stiffness matrix is broken down into two parts, one for lambda
        # and the other for mu, we'll separately compute them and then
        # combine.
        ke_lambda, fe_lambda, ke_mu, fe_mu = self._compute_hexahedron(
            dx / 2, dy / 2, dz / 2)

        number_of_nodes = (1 + n_el_x) * (1 + n_el_y) * (1 + n_el_z)

        # Applying the periodic boundary condition for periodic 
        # volmes. Here we apply the node numbers and degrees of freedom for 
        # this approximation.
        node_numbers = np.c_[np.arange(1, (number_of_nodes) + 1)]
        node_numbers = node_numbers.reshape(
            1 + n_el_x, 1 + n_el_y, 1 + n_el_z)
        
        degrees_of_freedom = 3 * node_numbers[0:node_numbers.shape[0]-1, 0:node_numbers.shape[1]-1, 0:node_numbers.shape[2]-1] + 1
        degrees_of_freedom = degrees_of_freedom.reshape(n_el, 1)

        mid = 3 * n_el_x + np.array([3, 4, 5, 0, 1, 2])
        add_x = np.concatenate((np.array([0, 1, 2]), mid, np.array([-3, -2, -1])))
        add_xy = 3 * (n_el_y + 1) * (n_el_x + 1) + add_x

        element_degrees_of_freedom = np.matlib.repmat(
            degrees_of_freedom, 1, 24) + np.matlib.repmat(
                np.concatenate([add_x, add_xy]), n_el, 1)

        # Impose Periodic Boundary Conditions
        number_unique_nodes = n_el

        unique_nodes_tensor = np.arange(1, number_unique_nodes + 1)
        unique_nodes_tensor = unique_nodes_tensor.reshape(n_el_x, n_el_y, n_el_z)
        back_border_cols = unique_nodes_tensor[:, :, 0]

        unt_indices = []
        for i, matrix in enumerate(unique_nodes_tensor):
            unt_indices.append(np.append(matrix, back_border_cols[i][...,None], 1))
        
        unique_nodes_tensor = np.array(unt_indices)

        left_border_cols = unique_nodes_tensor[:, 0, :]

        unt_indices = []
        for i, matrix in enumerate(unique_nodes_tensor):
            unt_indices.append(np.vstack([matrix, left_border_cols[i]]))
        
        unique_nodes_tensor = np.array(unt_indices)
        unique_nodes_tensor = np.concatenate((unique_nodes_tensor, unique_nodes_tensor[0][None]), axis=0)


        _dof = np.zeros((3 * number_of_nodes, 1))
        _uniq = unique_nodes_tensor.reshape(np.prod(unique_nodes_tensor.shape))
        for i in range(0, _dof.shape[0], 3):
            idx = i // 3
            _dof[i] = 3 * _uniq[idx] - 2
        
        for i in range(1, _dof.shape[0], 3):
            idx = i // 3
            _dof[i] = 3 * _uniq[idx] - 1

        for i in range(2, _dof.shape[0], 3):
            idx = i // 3
            _dof[i] = 3 * _uniq[idx]

        print(element_degrees_of_freedom - 1)

        print(_dof[element_degrees_of_freedom - 1].shape)


    def _compute_hexahedron(self, a: int, b: int, c: int) -> Hexahedron:
        """Compute hexahedron from 3d voxel shape grid

        Args:
            a (int): Dimension A (x direction)
            b (int): Dimension B (y direction) 
            c (int): Dimension C (z direction)
        """
        # Constitutive matrix contributions - Mu
        C_mu = np.diag([2, 2, 2, 1, 1, 1])

        # Constitutive matrix contribution - Lambda
        C_lambda = np.zeros((6, 6))
        C_lambda[0:3, 0:3] = 1

        # Calculate the three gauss points in all 3 directions
        xx = np.array([-math.sqrt(3/5), 0, math.sqrt(3/5)])
        yy = np.array([-math.sqrt(3/5), 0, math.sqrt(3/5)])
        zz = np.array([-math.sqrt(3/5), 0, math.sqrt(3/5)])
        ww = np.array([5/9, 8/9, 5/9])

        # Initialize
        ke_lambda = np.zeros((24, 24))
        fe_lambda = np.zeros((24, 6))

        ke_mu = np.zeros((24, 24))
        fe_mu = np.zeros((24, 6))

        # Begin integration over the volume
        for i in range(len(xx)):
            for j in range(len(yy)):
                for k in range(len(zz)):
                    # Integration point
                    x = xx[i]
                    y = yy[j]
                    z = zz[k]

                    # Compute the stress-strain displacement matrix
                qx = [
                    -((y-1)*(z-1))/8, 
                    ((y-1)*(z-1))/8, 
                    -((y+1)*(z-1))/8,
                    ((y+1)*(z-1))/8, 
                    ((y-1)*(z+1))/8,
                    -((y-1)*(z+1))/8,
                    ((y+1)*(z+1))/8, 
                    -((y+1)*(z+1))/8
                ]

                qy = [ 
                    -((x-1)*(z-1))/8,
                    ((x+1)*(z-1))/8,
                    -((x+1)*(z-1))/8,
                    ((x-1)*(z-1))/8,
                    ((x-1)*(z+1))/8, 
                    -((x+1)*(z+1))/8,
                    ((x+1)*(z+1))/8,
                    -((x-1)*(z+1))/8
                ]
                
                qz = [
                    -((x-1)*(y-1))/8,
                    ((x+1)*(y-1))/8, 
                    -((x+1)*(y+1))/8,
                    ((x-1)*(y+1))/8, 
                    ((x-1)*(y-1))/8, 
                    -((x+1)*(y-1))/8,
                    ((x+1)*(y+1))/8, 
                    -((x-1)*(y+1))/8
                ]

                # Compute the jacobian
                J = np.matmul(np.array([qz, qy, qz]), np.array([
                    [-a, a, a, -a, -a, a, a, -a],
                    [-b, -b, b, b, -b, -b, b, b],
                    [-c, -c, -c, -c, c, c, c, c],
                ]).transpose())

                qxyz = np.linalg.lstsq(J, qq)[0]
                B_e = np.zeros((8, 6, 3))

                for ii in range(B_e.shape[0]):
                    B_e[ii] = np.array([
                        [qxyz[0, ii], 0, 0],
                        [0, qxyz[1, ii], 0],
                        [0, 0, qxyz[2, ii]],
                        [qxyz[1, ii], qxyz[0, ii], 0],
                        [0, qxyz[2, ii], qxyz[1, ii]],
                        [qxyz[2, ii], 0, qxyz[0, ii]],
                    ])

                B = np.hstack([B_e[ii] for ii in range(B_e.shape[0])])

                weight = np.linalg.det(J) * ww[i] * ww[j] * ww[k]

                # Element matrices
                ke_lambda += weight * np.matmul(np.matmul(B.transpose(), C_lambda), B)
                ke_mu += weight * np.matmul(np.matmul(B.transpose(), C_mu), B)

                # Element loads
                fe_lambda += weight * np.matmul(B.transpose(), C_lambda)
                fe_mu += weight * np.matmul(B.transpose(), C_mu)
    
        return Hexahedron(ke_lambda, ke_mu, fe_lambda, fe_mu)



In [407]:


h = Homogenization(10, 10, 10, 0, 0, np.zeros((10, 10, 10)))
h.homogenize()


[[   3    4    5   36   37   38   33   34   35    0 ...  368  399  400  401  396  397  398  363  364  365]
 [   6    7    8   39   40   41   36   37   38    3 ...  371  402  403  404  399  400  401  366  367  368]
 [   9   10   11   42   43   44   39   40   41    6 ...  374  405  406  407  402  403  404  369  370  371]
 [  12   13   14   45   46   47   42   43   44    9 ...  377  408  409  410  405  406  407  372  373  374]
 [  15   16   17   48   49   50   45   46   47   12 ...  380  411  412  413  408  409  410  375  376  377]
 [  18   19   20   51   52   53   48   49   50   15 ...  383  414  415  416  411  412  413  378  379  380]
 [  21   22   23   54   55   56   51   52   53   18 ...  386  417  418  419  414  415  416  381  382  383]
 [  24   25   26   57   58   59   54   55   56   21 ...  389  420  421  422  417  418  419  384  385  386]
 [  27   28   29   60   61   62   57   58   59   24 ...  392  423  424  425  420  421  422  387  388  389]
 [  30   31   32   63   64   65   60 

<ipython-input-406-b58062eab2b7>:184: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  qxyz = np.linalg.lstsq(J, qq)[0]


IndexError: index 3993 is out of bounds for axis 0 with size 3993

In [164]:
C = np.zeros((6, 6))
C[0:3, 0:3] = 1
np.linalg.lstsq(C, C)[0]
x = 1
y = 2
z = 3
qx = [
    -((y-1)*(z-1))/8, 
    ((y-1)*(z-1))/8, 
    -((y+1)*(z-1))/8,
    ((y+1)*(z-1))/8, 
    ((y-1)*(z+1))/8,
    -((y-1)*(z+1))/8,
    ((y+1)*(z+1))/8, 
    -((y+1)*(z+1))/8
]

qy = [ 
    -((x-1)*(z-1))/8,
    ((x+1)*(z-1))/8,
    -((x+1)*(z-1))/8,
    ((x-1)*(z-1))/8,
    ((x-1)*(z+1))/8, 
    -((x+1)*(z+1))/8,
    ((x+1)*(z+1))/8,
    -((x-1)*(z+1))/8
]

qz = [
    -((x-1)*(y-1))/8,
    ((x+1)*(y-1))/8, 
    -((x+1)*(y+1))/8,
    ((x-1)*(y+1))/8, 
    ((x-1)*(y-1))/8, 
    -((x+1)*(y-1))/8,
    ((x+1)*(y+1))/8, 
    -((x-1)*(y+1))/8
]

qq = np.array([qx, qy, qz])
J = np.identity(3)
np.linalg.solve(J, qq)

qxyz = np.linalg.solve(J, qq) 
B_e = np.zeros((8, 6, 3))

for i in range(B_e.shape[0]):
    B_e[i] = np.array([
        [qxyz[0, i], 0, 0],
        [0, qxyz[1, i], 0],
        [0, 0, qxyz[2, i]],
        [qxyz[1, i], qxyz[0, i], 0],
        [0, qxyz[2, i], qxyz[1, i]],
        [qxyz[2, i], 0, qxyz[0, i]],
    ])

np.set_printoptions(edgeitems=10, linewidth=100000)
B = np.array([B_e[i] for i in range(B_e.shape[0])])
np.hstack([B_e[i] for i in range(B_e.shape[0])])

n_el_x = 100
n_el_y = 100
n_el_z = 100

print(n_el_x * n_el_y * n_el_z)
node_numbers = np.c_[np.arange(1, ((1 + n_el_x) * (1 + n_el_y) * (1 + n_el_z)) + 1)]
node_numbers = node_numbers.reshape(
    1 + n_el_x, 1 + n_el_y, 1 + n_el_z)

1000000


<ipython-input-164-8ee70230bad6>:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(C, C)[0]
